[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cdmodel"
version = "0.0.1"
authors = [
  { name="Author Name", email="email@example.com" },
]
description = "description"
readme = "README.md"
requires-python = ">=3.13.1"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "jsonargparse[signatures]==4.40.0",
    "lightning==2.5.1.post0",
    "matplotlib==3.10.3",
    "mypy-extensions==1.1.0",
    "numpy==2.3.0",
    "openpyxl==3.1.5",
    "pandas==2.3.0",
    "pandas-stubs==2.2.3.250527",
    "pqdm==0.2.0",
    "praat-parselmouth==0.4.6",
    "pytest==8.4.0",
    "pytest-mock==3.14.1",
    "pytest-cov==6.2.1",
    "scikit-learn==1.7.0",
    "scipy==1.15.3",
    "seaborn==0.13.2",
    "speech-utils @ git+https://github.com/mattm458/speech-utils.git",
    "statsmodels==0.14.4",
    "tensorboard==2.19.0",
    "torch==2.7.1",
    "transformers==4.52.4",
]

[tool.setuptools.package-data]
"cdmodel" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
"Homepage" = "https://github.com/mattm458/ml-template"
"Bug Tracker" = "https://github.com/mattm458/ml-template/issues"

[project.scripts]
cdmodel = "cdmodel.main:cli_main"
analysis = "cdmodel.analysis_main:cli_analysis"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
testpaths = ["tests"]