[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cdmodel"
version = "0.0.1"
authors = [
  { name="Author Name", email="email@example.com" },
]
description = "description"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "jsonargparse[signatures]==4.34.1",
    "lightning==2.4.0",
    "matplotlib==3.9.3",
    "mypy-extensions==1.0.0",
    "numpy==2.2.0",
    "pandas==2.2.3",
    "pandas-stubs==2.2.3.241126",
    "pqdm==0.2.0",
    "praat-parselmouth==0.4.5",
    "pytest==8.3.4",
    "pytest-mock==3.14.0",
    "scikit-learn==1.6.0",
    "scipy==1.14.1",
    "seaborn==0.13.2",
    "speech-utils @ git+https://github.com/mattm458/speech-utils.git",
    "statsmodels==0.14.4",
    "tensorboard==2.18.0",
    "torch==2.5.1",
]

[tool.setuptools.package-data]
"cdmodel" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
"Homepage" = "https://github.com/mattm458/ml-template"
"Bug Tracker" = "https://github.com/mattm458/ml-template/issues"

[project.scripts]
cdmodel = "cdmodel.main:cli_main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
testpaths = "tests"